from __future__ import annotations
from dataclasses import asdict
from pathlib import Path
import json,numpy as np,pandas as pd
from quant_pipeline.forensics.distribution import distribution_stats,contribution_concentration
from quant_pipeline.forensics.interaction import interaction_decomposition
from quant_pipeline.forensics.opportunities import build_episodes,independent_entries_fixed_hold
from quant_pipeline.forensics.redundancy import signal_jaccard
from quant_pipeline.production.outputs import ProductionData

def _table(path,rows): pd.DataFrame(rows).to_parquet(path,index=False)

def build_candidate_dossiers(*,legacy_run,candidates:pd.DataFrame,candidate_summary:pd.DataFrame,duals:pd.DataFrame,specialist:pd.DataFrame):
    data=ProductionData(legacy_run); root=legacy_run.root/"candidates"; root.mkdir(exist_ok=True); masks={}; built=[]
    for candidate in candidates.to_dict("records"):
        row=candidate_summary[candidate_summary.candidate_id.eq(candidate["candidate_id"])].iloc[0].to_dict(); grid,obs,a,b,y,mask,a_cell,b_cell=data.selected(row); masks[candidate["candidate_id"]]=(grid,mask); target=data.targets[candidate["target_id"]]; hold_value=int(target.horizon.value or 1); hold_ns=int(hold_value*(60e9 if target.horizon.kind=="minutes" else 24*60*60e9)); session_codes=pd.factorize(obs.session_date,sort=True)[0]; seq=obs.groupby("security_id",sort=False).cumcount().to_numpy(); eps=build_episodes(obs_id=obs.observation_id.to_numpy(),security_id=pd.factorize(obs.security_id,sort=True)[0],session_id=session_codes,security_session_seq=seq,decision_ts_ns=obs.decision_ts.astype("int64").to_numpy(),active=mask); opportunities=independent_entries_fixed_hold(episodes=eps,hold_ns=hold_ns); positions=np.asarray([x.start_obs_id for x in opportunities],dtype=np.int64); index_by_id=pd.Series(np.arange(len(obs)),index=obs.observation_id).to_dict(); pos=np.asarray([index_by_id[x] for x in positions if x in index_by_id],dtype=int); returns=y[pos]*10_000.0 if len(pos) else np.asarray([],dtype=float); dossier=root/candidate["candidate_id"]/"dossier"; dossier.mkdir(parents=True,exist_ok=True); dist=distribution_stats(returns); concentration=contribution_concentration(returns); interaction=interaction_decomposition(target_bps=y*10_000.0,active_a=a==a_cell,active_b=b==b_cell); sessions=max(1,obs.session_date.nunique()); starts=np.asarray([x.start_ts_ns for x in opportunities],dtype=np.int64); concurrency=[]
        for timestamp in starts: concurrency.append(int(np.sum((starts<=timestamp)&(starts+hold_ns>timestamp))))
        summary={"candidate_id":candidate["candidate_id"],"return_basis":candidate["return_basis"],"resolution":candidate["resolution"],"direction":candidate["direction"],"active_observation_count":int(mask.sum()),"selected_n":int(row["selected_n"]),"selected_frequency":float(row["selected_frequency"]),"selected_state_bps":float(row["selected_state_bps"]),"selected_interaction_lift_bps":float(row["selected_interaction_lift_bps"]),"weighted_state_contribution_bps":float(row["weighted_state_contribution_bps"]),"weighted_interaction_contribution_bps":float(row["weighted_interaction_contribution_bps"]),"episode_count":len(eps),"fresh_signal_count":len(eps),"independent_opportunity_count":len(opportunities),"eligible_session_count":sessions,"opportunities_per_day":len(opportunities)/sessions,"average_concurrency":float(np.mean(concurrency)) if concurrency else 0.0,"peak_concurrency":max(concurrency,default=0),"simultaneous_cluster_count":int(sum(x>1 for x in concurrency)),"break_even_round_trip_bps":abs(float(row["selected_state_bps"])),"break_even_per_side_bps":abs(float(row["selected_state_bps"]))/2,"evidence_role":"discovery_diagnostic",**dist,**concentration}; _table(dossier/"summary.parquet",[summary]); _table(dossier/"distribution.parquet",[{"candidate_id":candidate["candidate_id"],**dist,"evidence_role":"discovery_diagnostic"}]); _table(dossier/"episodes.parquet",[{**asdict(x),"evidence_role":"discovery_diagnostic"} for x in eps])
        chronology=[]
        if len(pos):
            selected=obs.iloc[pos].copy(); selected["return_bps"]=returns; selected["month"]=pd.to_datetime(selected.session_date).dt.to_period("M").astype(str)
            for month,part in selected.groupby("month"): chronology.append({"candidate_id":candidate["candidate_id"],"month":month,"n":len(part),"mean_bps":float(part.return_bps.mean()),"evidence_role":"discovery_diagnostic"})
        _table(dossier/"chronology.parquet",chronology or [{"candidate_id":candidate["candidate_id"],"month":None,"n":0,"mean_bps":None,"evidence_role":"discovery_diagnostic"}])
        counts=np.asarray(row["surface_counts"]); means=np.asarray(row["surface_means"]); lifts=np.asarray(row["incremental_surface"]); surface=[{"candidate_id":candidate["candidate_id"],"state_a":i//candidate["resolution"],"state_b":i%candidate["resolution"],"n":int(counts[i]),"mean_bps":float(means[i]*10_000) if np.isfinite(means[i]) else None,"interaction_lift_bps":float(lifts[i]*10_000) if np.isfinite(lifts[i]) else None,"evidence_role":"discovery_diagnostic"} for i in range(len(counts))]; _table(dossier/"surface_cells.parquet",surface)
        comparison=duals[(duals.pair_id==row["pair_id"])&(duals.target_id==row["target_id"])]; _table(dossier/"resolution_comparison.parquet",[{"candidate_id":candidate["candidate_id"],"resolution":int(x.v3_resolution),"selected_cell":int(x.selected_cell),"selected_state_bps":float(x.selected_state_bps),"selected_interaction_lift_bps":float(x.selected_interaction_lift_bps),"selected_frequency":float(x.selected_frequency),"selected_n":int(x.selected_n),"surface_spread_bps":float((x.best_cell_effect-x.worst_cell_effect)*10_000),"neighbor_effect_retention":float(x.neighbor_effect_retention),"plateau_area":int(x.plateau_area),"evidence_role":"discovery_diagnostic"} for x in comparison.itertuples()])
        ranked=np.sort(returns)[::-1] if len(returns) else returns; _table(dossier/"tail_ladder.parquet",[{"candidate_id":candidate["candidate_id"],"tail_percent":p,"n":max(1,int(np.ceil(len(ranked)*p/100))) if len(ranked) else 0,"contribution_bps":float(ranked[:max(1,int(np.ceil(len(ranked)*p/100)))].sum()) if len(ranked) else 0.0,"evidence_role":"discovery_diagnostic"} for p in (20,10,5,2,1)])
        horizons=[]
        for target_id,spec in data.targets.items():
            if spec.decision_grid!=grid:continue
            values=data.target(grid,target_id); local=values[mask]*10_000.0; horizons.append({"candidate_id":candidate["candidate_id"],"target_id":target_id,"horizon":spec.horizon.label,"n":int(np.isfinite(local).sum()),"mean_bps":float(np.nanmean(local)) if np.isfinite(local).any() else None,"evidence_role":"discovery_diagnostic"})
        _table(dossier/"horizon_ladder.parquet",horizons); event=sorted(horizons,key=lambda x:data.targets[x["target_id"]].horizon.value or 10**9); peak=max((x for x in event if x["mean_bps"] is not None),key=lambda x:abs(x["mean_bps"]),default=None); _table(dossier/"event_path.parquet",[{**x,"time_to_25pct":None,"time_to_50pct":None,"time_to_75pct":None,"time_to_peak":peak["horizon"] if peak else None,"post_peak_giveback_bps":None} for x in event])
        symbol=[]
        if len(pos):
            selected=obs.iloc[pos].copy(); selected["return_bps"]=returns
            for security,part in selected.groupby("security_id"): symbol.append({"candidate_id":candidate["candidate_id"],"security_id":security,"n":len(part),"mean_bps":float(part.return_bps.mean()),"evidence_role":"discovery_diagnostic"})
        _table(dossier/"symbol_breakdown.parquet",symbol or [{"candidate_id":candidate["candidate_id"],"security_id":None,"n":0,"mean_bps":None,"evidence_role":"discovery_diagnostic"}]); sp=specialist[(specialist.pair_id==row["pair_id"])&(specialist.target_id==row["target_id"])&(specialist.resolution==candidate["resolution"])]; sp.assign(candidate_id=candidate["candidate_id"],evidence_role="discovery_diagnostic").to_parquet(dossier/"specialist.parquet",index=False); _table(dossier/"concentration.parquet",[{"candidate_id":candidate["candidate_id"],**concentration,"evidence_role":"discovery_diagnostic"}]); _table(dossier/"interaction.parquet",[{"candidate_id":candidate["candidate_id"],**interaction,"evidence_role":"discovery_diagnostic"}])
        target_ledger=legacy_run.root/"cache"/"targets"/f"{grid}.parquet"; ledger=pd.read_parquet(target_ledger,filters=[("target_id","=",candidate["target_id"])])[["observation_id","entry_ts","exit_ts"]]; signals=obs.loc[mask,["observation_id","security_id","decision_ts"]].merge(ledger,on="observation_id",how="left"); security=pd.read_parquet(Path(legacy_run.config.project_root)/"reference/security_master.parquet",columns=["security_id","symbol"]); signals=signals.merge(security.drop_duplicates("security_id"),on="security_id",how="left"); signals["candidate_id"]=candidate["candidate_id"]; signals["signal_timestamp"]=signals.decision_ts; signals["reference_exit_timestamp"]=signals.exit_ts; signals["direction"]=candidate["direction"]; signals["resolution"]=candidate["resolution"]; signals["state_payload"]=json.dumps(candidate["state_payload"],sort_keys=True); signals.to_parquet(dossier/"signals.parquet",index=False); built.append(candidate["candidate_id"]); (dossier/"dossier.json").write_text(json.dumps({"candidate_id":candidate["candidate_id"],"definition_hash":candidate["definition_hash"],"evidence_role":"discovery_diagnostic","files":sorted(x.name for x in dossier.iterdir())},indent=2,default=str),encoding="utf-8")
    for candidate_id,(grid,mask) in masks.items():
        peers=[{"candidate_id":other,"signal_jaccard":signal_jaccard(mask,other_mask)} for other,(other_grid,other_mask) in masks.items() if other!=candidate_id and other_grid==grid]; _table(root/candidate_id/"dossier"/"redundancy.parquet",peers or [{"candidate_id":None,"signal_jaccard":None}])
    if len(candidates): candidates=candidates.copy(); candidates["status"]="dossier_complete"; candidates["dossier_status"]="complete"; candidates.to_parquet(legacy_run.root/"edge_registry.parquet",index=False)
    return built
