from pathlib import Path
import pandas as pd,json
O=Path('D:/AlgoResearch/Quant-Pipeline-V3/runs/v3_comprehensive_20260923/research/intraday_strategy_20260928');D=O/'direct_lag_both_legs'
s=pd.read_parquet(D/'both_legs_summary.parquet');r=pd.read_parquet(D/'both_legs_replays.parquet');b=pd.read_parquet(O/'direct_market_lag/results.parquet');rules=pd.read_parquet(O/'direct_market_lag/rules.parquet');manifest=pd.read_parquet(O/'direct_lag_quote_sample/manifest.parquet');axes=json.loads((O/'price_axes.json').read_text());stats=[]
for strategy,g in s.groupby('strategy'):
 best=g.sort_values('bps_attempt',ascending=False).iloc[0];tr=r[(r.strategy==strategy)&(r.entry_method==best.entry_method)&(r.exit_method==best.exit_method)].copy();tr['month']=[str(axes['days'][d])[:7] for d in tr.day]
 market=g[(g.entry_method=='market')&(g.exit_method=='market')].iloc[0]
 stats.append({'id':int(strategy.replace('mechanism','')),'market_bps_attempt':market.bps_attempt,'buy_offset':best.entry_method,'sell_offset':best.exit_method,'best_bps_attempt':best.bps_attempt,'fills':int(best.entry_fills),'attempts':int(best.attempts),'scheduled':int((manifest.strategy==strategy).sum()),'positive_sample_months':int((tr.groupby('month').bps.sum()>0).sum()),'trim3_bps_attempt':tr.bps.nsmallest(len(tr)-3).sum()/len(tr),'limit_exits':int(best.exit_limit_fills),'fallback_exits':int(best.exit_fallbacks)})
f=pd.DataFrame(stats);f.to_parquet(D/'decision_summary.parquet',index=False);print(f.to_string(index=False))
text='# Direct market lag and overshoot - 2026-09-28\n\n24 fixed rules: lag versus overshoot, 5/15-minute lookbacks, SPY moves exceeding 5/10 bp, beta-adjusted stock deviations beyond 5 bp, 2/5/15-minute holds. Lag trades with market direction; overshoot trades against it. Beta uses the preceding 20 sessions only, nonoverlapping 5-minute open returns, minimum 100 valid observations, clipped to [0,3]. First 20 discovery sessions warm up; full-calendar denominator retained. SPY/QQQ excluded as trading stocks. Signals observe raw opens, enter one minute later and exit at least five minutes before close. Missing scheduled bar exits advance to the next available open before cutoff.\n\nTested 1/5/10 slots and 25/50/100% capital at -1,0,1,2,3,4,5 bp per side; 72 rule/slot schedules. No ticker/time filters. GPU beta and signal calculations. Rules 9/23 selected as frequent overshoot diagnostics despite failing half-period bar stability; rule 24 is the strongest best-five-days-trimmed top-one configuration with both bar halves positive.\n\n## Quote execution\n\nSix seeded random trades/month (seed 20260928), all 64 entry/exit combinations. Quotes use historical-date symbol mapping. Passive executable-side move-through is a fill proxy without queue/size validation. Entry cancels after 60 seconds; exit markets after 60 seconds if unfilled, capped five minutes before close. Positive entry offsets improve entry price, positive exit offsets improve exit price relative to scheduled midpoint, with conservative cent rounding. Long and short sides included. No extra cost or rebate overlay. No annualization. These frozen sampled schedules do not recycle canceled capital or resolve conflicts from extended exits.\n\n| Rule | Coverage | Market bps/attempt | Best entry/exit offsets | Best bps/attempt | Fills | Positive sampled months | Excluding best 3 trades |\n|---|---:|---:|---|---:|---:|---:|---:|\n'
for t in f.itertuples():text+=f'| {t.id} | {t.attempts}/{t.scheduled} | {t.market_bps_attempt:.3f} | {t.buy_offset}/{t.sell_offset} | {t.best_bps_attempt:.3f} | {t.fills} | {t.positive_sample_months}/12 | {t.trim3_bps_attempt:.3f} |\n'
text+='\nGrid maxima are selected discovery results, not proven execution policies.\n\n## Bar diagnostics\n\n'
for ident in [9,23,24]:
 rule=rules[rules.mechanism_id==ident].iloc[0];slots=1 if ident==24 else 5;v=b[(b.mechanism_id==ident)&(b.slots==slots)&(b.capital==1)&(b.cost==0)].iloc[0]
 text+=f'- Rule {ident}: {rule.mechanism}, {rule.lookback}m lookback, SPY move {rule.market_threshold_bps} bp, {rule.horizon}m hold, {slots} slots. Zero-cost bar return {v.return_pct:.2f}%, daily DD {v.daily_dd_pct:.2f}%, {v.trades_day:.2f} trades/day, {v.positive_months}/12 positive months.\n'
text+='\nRule 23 reaches 12 positive months under hypothetical -1 bp/side costs; that is not an observed rebate. All bar diagnostics remain distinct from quote execution.\n\nArtifacts: '+str(O)+' under direct_market_lag, direct_lag_quote_sample and direct_lag_both_legs. Full grids and trade ledgers saved. May 2026 onward untouched.\n'
Path('docs/research/V3_DIRECT_MARKET_LAG_2026-09-28.md').write_text(text,encoding='utf-8')
p=Path('docs/research/RESEARCH_INDEX.md');t=p.read_text(encoding='utf-8');link='V3_DIRECT_MARKET_LAG_2026-09-28.md'
if link not in t:p.write_text(t+'\n## Direct market lag/overshoot\n\n[24 fixed rules and execution diagnostics]('+link+'). Prior-day beta only; complete cost grids and sampled buy/sell quote tests saved.\n',encoding='utf-8')
