from pathlib import Path
import pandas as pd,json,numpy as np
O=Path('D:/AlgoResearch/Quant-Pipeline-V3/runs/v3_comprehensive_20260923/research/intraday_strategy_20260928');D=O/'round2_both_legs'
s=pd.read_parquet(D/'both_legs_summary.parquet');r=pd.read_parquet(D/'both_legs_replays.parquet');b=pd.read_parquet(O/'mechanism_round2/results.parquet');rules=pd.read_parquet(O/'mechanism_round2/rules.parquet');manifest=pd.read_parquet(O/'round2_quote_sample/manifest.parquet');stats=[]
for strategy,g in s.groupby('strategy'):
 best=g.sort_values('bps_attempt',ascending=False).iloc[0];tr=r[(r.strategy==strategy)&(r.entry_method==best.entry_method)&(r.exit_method==best.exit_method)].copy()
 tr['month']=[str(json.loads((O/'price_axes.json').read_text())['days'][d])[:7] for d in tr.day]
 ident=int(strategy.replace('mechanism',''));market=g[(g.entry_method=='market')&(g.exit_method=='market')].iloc[0]
 stats.append({'id':ident,'market_bps_attempt':market.bps_attempt,'buy_offset':best.entry_method,'sell_offset':best.exit_method,'best_bps_attempt':best.bps_attempt,'fills':int(best.entry_fills),'attempts':int(best.attempts),'scheduled':int((manifest.strategy==strategy).sum()),'positive_sample_months':int((tr.groupby('month').bps.sum()>0).sum()),'trim3_bps_attempt':tr.bps.nsmallest(len(tr)-3).sum()/len(tr),'limit_exits':int(best.exit_limit_fills),'fallback_exits':int(best.exit_fallbacks)})
f=pd.DataFrame(stats);f.to_parquet(D/'decision_summary.parquet',index=False);print(f.to_string(index=False))
text='# Mechanism round 2 — 2026-09-28\n\n'
text+='Screened 18 previously unreplayed pairs across market response/relative strength, price-volume dislocations, and volume confirmation, with r10 and broader r5 cells (36 rules). Used existing global neighbor, residual-return, and benchmark-adjusted sign screens. No new time/ticker filters. Replayed 1/5/10 positions, 25/50/100% capital, and -1,0,1,2,3,4,5 bps per side. All results are discovery only.\n\n'
text+='## Quote results\n\nThree candidates passed initial two-half, concentration and monthly screens. Six seeded random eligible trades/month/candidate, seed 20260928; fixed neutral five-slot schedules. Each tested with the complete 64 buy/sell market-or-limit combinations. Entry cancellation after 60 seconds; exit market fallback after 60 seconds, capped five minutes before close. Positive buy offset bids below midpoint; positive sell offset offers above midpoint. Returns use quote prices without hypothetical fee/rebate overlays. Strict executable-side move-through is a passive fill proxy, not established queue/size fillability. Sample results are not annualized.\n\n'
text+='| Rule | Quote coverage | Market bps/attempt | Best buy/sell offsets | Best bps/attempt | Fills | Positive sampled months | Remove best 3 trades |\n|---|---:|---:|---|---:|---:|---:|---:|\n'
for t in f.itertuples():text+=f'| {t.id} | {t.attempts}/{t.scheduled} | {t.market_bps_attempt:.3f} | {t.buy_offset}/{t.sell_offset} | {t.best_bps_attempt:.3f} | {t.fills} | {t.positive_sample_months}/12 | {t.trim3_bps_attempt:.3f} |\n'
text+='\nBest grid cells are selected discovery maxima, not proven execution policies. Reject concentrated or negative outcomes rather than tune around them. Frozen sampled schedules do not model opportunities freed by canceled orders or conflicts introduced by extended exits; full event-driven replay is required before portfolio claims.\n\n## Definitions and bar diagnostics\n\n'
for ident in [5,11,31]:
 rule=rules[rules.mechanism_id==ident].iloc[0];v=b[(b.mechanism_id==ident)&(b.slots==5)&(b.capital==1)&(b.cost==0)].iloc[0]
 text+=f'- Rule {ident}: {rule.feature_a} × {rule.feature_b}, r{rule.resolution} cell {rule.cell}, direction {rule.direction}, hold {rule.horizon}m. Bar zero-cost {v.return_pct:.2f}%, daily drawdown {v.daily_dd_pct:.2f}%, {v.trades_day:.2f} trades/day, {v.positive_months}/12 months. These are bar diagnostics, not quote returns.\n'
text+='\nAll three remain bar-profitable excluding the best three tickers and five days. Both halves are positive for these definitions; rule 31 narrower r10 neighbor fails the second half, so its stability is weaker. No sector-specific feature was introduced and these tests do not establish a causal market lead mechanism. Feature definitions inspected use trailing/current inputs; this is not a fresh full prefix-recomputation audit.\n\nArtifacts: `'+str(O)+'` under `mechanism_round2`, `round2_quote_sample`, and `round2_both_legs`. Complete cost grids, trade ledgers, 64-cell quote grids, monthly quote summaries, and identity flags saved. May 2026 onward untouched.\n'
Path('docs/research/V3_MECHANISM_ROUND2_2026-09-28.md').write_text(text,encoding='utf-8')
p=Path('docs/research/RESEARCH_INDEX.md');t=p.read_text(encoding='utf-8');link='V3_MECHANISM_ROUND2_2026-09-28.md'
if link not in t:p.write_text(t+'\n## Mechanism round 2\n\n[36 new rules and complete buy/sell quote grids]('+link+'). Covers market response, price-volume dislocation and volume confirmation; raw ledgers and concentration checks saved.\n',encoding='utf-8')
