from pathlib import Path
import pandas as pd,numpy as np,json
O=Path('D:/AlgoResearch/Quant-Pipeline-V3/runs/v3_comprehensive_20260923/research/intraday_strategy_20260928');D=O/'mechanism_consistency';Q=O/'mechanism_quote_sample'
s=pd.read_parquet(D/'results.parquet');rules=pd.read_parquet(D/'rules.parquet');q=pd.read_parquet(Q/'replays.parquet');summary=pd.read_parquet(Q/'summary.parquet');filtered=[]
for cap in [1,2,5]:
 for (strategy,method),g in q.groupby(['strategy','method']):
  z=g[g.arrival_spread_bps<=cap];filled=z[z.filled]
  filtered.append({'strategy':strategy,'method':method,'spread_cap':cap,'eligible':len(z),'fills':len(filled),'bps_per_eligible':z.bps.mean(),'bps_per_original_attempt':z.bps.sum()/len(g),'bps_per_fill':filled.bps.mean()})
f=pd.DataFrame(filtered);f.to_parquet(Q/'spread_filters.parquet',index=False)
lines=['# Mechanism-first consistency research','', 'Goal: find recurring per-trade expectancy, then adjust slots, frequency and capital. Lower exposure cannot repair negative expectancy. All-positive discovery months are descriptive, not proof of a stable edge.','', 'Screened short-hold (1-30minute) non-EMA definitions with at least2500 observations and100 observations per month; ranked monthly downside and selected24 distinct feature-pair definitions with11-12 positive pooled months. This is explicitly discovery selection, not an independent consistency test. Replayed neutral deterministic and prior-move ranking,1/5/10slots,25/50/100%total capital, and all seven bar-cost assumptions. Neutral ranks use a deterministic security hash, not future returns. Capital is divided across slots using day-start equity. Missing scheduled exit bars execute at the first subsequent available minute open before the close buffer; complete ledgers are saved.','', '## Mechanism hypotheses','', '- Opening failed-breakout/price-path reversal: ten-minute long entries conditioned on a spread proxy and failed-breakout state (mechanism2); downside-run variant (9).','- Afternoon reversal: ten-minute longs conditioned on path convexity and negative acceleration (11).','- Morning burst exhaustion: two-minute shorts conditioned on fast-minus-slow returns and positive-jump fraction (19).','- Late-session short drift: thirty-minute shorts conditioned on a spread proxy and information discreteness (10), or permutation entropy (12).','', 'These descriptions are hypotheses from signal definitions, not causal explanations established by the backtest. Neighbor analysis is saved: mechanism11 has positive adjacent-cell means but only10 positive months; mechanism19 has one similarly positive neighbor and one sharply negative neighbor; mechanism2 is locally fragile.','', '## Bar-reference examples, zero assumed cost','', '| Mechanism | Slots | Trades/day | Return | Daily-close DD | Positive months |','|---|---:|---:|---:|---:|---:|']
configs=[(2,'neutral',10),(11,'recent_move',10),(19,'neutral',5),(9,'recent_move',1),(10,'neutral',5),(12,'neutral',10)]
for ident,rank,slots in configs:
 z=s[(s.mechanism_id==ident)&(s.ranking==rank)&(s.slots==slots)&(s.capital==1)&(s.cost==0)].iloc[0];lines.append(f'| {ident} | {slots} | {z.trades_day:.2f} | {z.return_pct:.2f}% | {z.daily_dd_pct:.2f}% | {z.positive_months}/12 |')
lines+=['','The first three have12 positive months in the bar replay but very thin margins; at+1bp/side, mechanism2 is+0.43%,11 is-15.05%,19 is+0.02%. Reducing capital changes profit/drawdown scale, not the underlying execution problem. Daily-close drawdowns exclude intraday excursions.','', '## Quote diagnostic','', 'Four predetermined ledger indices per month per candidate,288scheduled sample trades. No profit-based sample selection. Market plus seven midpoint-relative limit offsets.60second wait; no hypothetical fee/rebate overlay. Passive fills require strict move-through; missing quote states are explicitly listed in missing.json. This is a marginal-order fill proxy, not a portfolio or queue simulation. Frozen timestamps allow comparable execution testing but do not regenerate signals after unfilled orders.','', '| Mechanism | Entry | Fills/covered attempts | Bps/fill | Bps/attempt |','|---|---|---:|---:|---:|']
for z in summary.itertuples():lines.append(f'| {z.strategy} | {z.method} | {z.fills}/{z.attempts} | {z.bps_fill:.2f} | {z.bps_attempt:.2f} |')
lines+=['','## Preset spread screens','', 'Arrival spreads at most1,2,5bps, applied before entry; skipped signals earn zero per original attempt. The entire table is saved in spread_filters.parquet. These are exploratory sample diagnostics; choosing a profitable tiny subset is not validation.','']
print('SPREAD FILTER BEST WITH >=12 FILLS');print(f[f.fills>=12].sort_values('bps_per_original_attempt',ascending=False).head(12).to_string(index=False))
for z in f[f.fills>=12].sort_values('bps_per_original_attempt',ascending=False).head(8).itertuples():lines.append(f'- {z.strategy},offset{z.method},spread<={z.spread_cap}bps:{z.fills}/{z.eligible}fills,+{z.bps_per_original_attempt:.2f}bps per original attempt ({z.bps_per_fill:.2f}bps/fill).')
lines+=['','## Artifacts','', 'mechanism_consistency/:rules.parquet,results.parquet,trades.parquet,neighbors.parquet. mechanism_quote_sample/:manifest.parquet,replays.parquet,summary.parquet,spread_filters.parquet,missing.json,raw quotes. Scripts:intraday_mechanism_consistency.py,intraday_mechanism_quotes.py,intraday_mechanism_report.py. May2026+ untouched.']
Path('docs/research/V3_MECHANISM_CONSISTENCY_2026-09-28.md').write_text('\n'.join(lines)+'\n')
