from intraday_strategy_search import connection,OUT
import pandas as pd
c=connection();p=(OUT/'all_cells.parquet').as_posix()
c.execute(f"create view allcells as select * from read_parquet('{p}')")
c.execute("""create temp table raw as select *,sum_bps/n gross,sign(sum_bps)::int direction,cast(regexp_extract(target_id,'target_([0-9]+)m',1) as int) horizon from allcells where resolution=10 and target_id in ('target_1m__raw__intraday_5m','target_2m__raw__intraday_5m','target_5m__raw__intraday_5m','target_10m__raw__intraday_5m','target_15m__raw__intraday_5m','target_30m__raw__intraday_5m','target_60m__raw__intraday_5m') and n>=1000 and not contains(feature_a,'ema_distance') and not contains(feature_b,'ema_distance')""")
print('GLOBAL CELLS',c.execute('select count(*),count(distinct pair_id) from raw').fetchone(),flush=True)
c.execute("""create temp table neighbors as select a.pair_id,a.target_id,a.cell,count(*) neighbors,min(b.gross*a.direction) neighbor_min,avg(b.gross*a.direction) neighbor_mean from raw a join raw b on a.pair_id=b.pair_id and a.target_id=b.target_id and abs(a.cell//10-b.cell//10)+abs(a.cell%10-b.cell%10)=1 where abs(a.gross)>=4 group by 1,2,3""")
f=c.execute("""select a.*,n.neighbors,n.neighbor_min,n.neighbor_mean,p.sum_bps/p.n*a.direction coarse_mean,z.sum_bps/z.n*a.direction residual_mean,v.sum_bps/v.n*a.direction benchmark_mean,least(abs(a.gross),n.neighbor_mean,p.sum_bps/p.n*a.direction,z.sum_bps/z.n*a.direction)/sqrt(a.horizon)*ln(a.n) score from raw a join neighbors n using(pair_id,target_id,cell) join allcells p on p.pair_id=a.pair_id and p.target_id=a.target_id and p.resolution=5 and p.cell=(a.cell//20)*5+(a.cell%10)//2 join allcells z on z.pair_id=a.pair_id and z.target_id=replace(a.target_id,'__raw__','__beta_residual__') and z.resolution=10 and z.cell=a.cell join allcells v on v.pair_id=a.pair_id and v.target_id=replace(a.target_id,'__raw__','__benchmark_adjusted__') and v.resolution=10 and v.cell=a.cell where n.neighbors>=2 and n.neighbor_min>0 and coarse_mean>0 and residual_mean>0 and benchmark_mean>0 order by score desc""").df()
f.to_parquet(OUT/'global_stable_surfaces.parquet',index=False)
old=pd.read_parquet(OUT/'pair_shortlist.parquet');f=f[~f.pair_id.isin(old.pair_id)].drop_duplicates('pair_id');f['family']=f.feature_a.str.split('__').str[0];chosen=f.groupby('family',sort=False).head(2).head(48);chosen[['pair_id','feature_a','feature_b']].to_parquet(OUT/'stable_pair_shortlist.parquet',index=False)
print('stable',len(f),'new followups',len(chosen));print(chosen[['feature_a','feature_b','horizon','cell','gross','neighbor_min','coarse_mean','residual_mean','score']].head(15).to_string(index=False))

