from pathlib import Path
import pandas as pd,numpy as np,json,sys
O=Path('D:/AlgoResearch/Quant-Pipeline-V3/runs/v3_comprehensive_20260923/research/intraday_strategy_20260928');full='--leaders-full' in sys.argv;D=O/('quote_leaders_full' if full else 'quote_expanded')
s=pd.read_parquet(D/'summary.parquet');m=pd.read_parquet(D/'manifest.parquet');r=pd.read_parquet(D/'replays.parquet');missing=json.loads((D/'missing.json').read_text());d=pd.read_parquet(D/'daily.parquet')
n_days=len(json.loads((D/'design.json').read_text())['days'])
lines=['# Expanded quote comparison','',f'{n_days} discovery sessions; {len(m)} scheduled trades across {m.strategy.nunique()} candidates. {len(m)-len(missing)} have usable quote windows; {len(missing)} are excluded. No May 2026+ data. No hypothetical cost overlay. All exits remain intraday.','', '## Method and limits','', 'Market entry and seven midpoint-relative limit offsets (-1,0,1,2,3,4,5 bps); positive offset demands a better entry in the trade direction. Whole-cent rounding. Latest valid quote within five seconds before arrival, otherwise first valid quote within one second after. Marketable limits execute at quoted ask for buys or bid for sells. Passive orders require strict executable-side move-through within 60 seconds, filled at the limit. Scheduled exits use opposite-side quote. No-fill attempts earn zero.','', 'One position uses full current equity sequentially; pending orders reserve capital for 60 seconds. Combined strategies prioritize the named engine at simultaneous arrivals. These are frozen standalone signal schedules: signals previously blocked by standalone positions are not regenerated after missed fills or portfolio conflicts. Consequently this is a schedule-based comparison, not a complete live signal-union backtest. Missing quote trades are excluded, making P&L incomplete; coverage is shown below. Quote fills are marginal small-order proxies, not proof of full-equity capacity. Queue, latency, borrow, and actual fees/rebates are not modeled.','', '## Coverage','']
for name,g in m.groupby('strategy'):lines.append(f'- {name}: {len(g)-sum(i in missing for i in g.index)}/{len(g)} usable scheduled trades.')
lines+=['','## All results','', 'Bps/day averages over all selected days, including idle days. The 24-session diagnostic uses two sessions per month; the full-year run uses every session. Sample return compounds those sessions only, never annualized. Missing trades are not evidence of zero return.','', '| Candidate | Offset | Fills/attempts | Bps/fill | Bps/attempt | Bps/day | Positive sampled months | First/second half bps/day |','|---|---|---:|---:|---:|---:|---:|---:|']
for t in s.itertuples():lines.append(f'| {t.strategy} | {t.method} | {t.fills}/{t.attempts} | {t.bps_per_fill:.2f} | {t.bps_per_attempt:.2f} | {t.bps_per_sample_day:.2f} | {t.positive_months}/12 | {t.first_half_bps_day:.2f} / {t.second_half_bps_day:.2f} |')
lines+=['','## Concentration and uncertainty','', 'Descriptive 95% bootstrap intervals resample the daily returns (5,000 draws, seed 20260928); they do not correct candidate selection or establish out-of-sample evidence.']
rng=np.random.default_rng(20260928)
for name,g in s.groupby('strategy'):
 best=g.sort_values('bps_per_sample_day',ascending=False).iloc[0];v=d[(d.strategy==name)&(d.method==best.method)]['return'].to_numpy()*10000;ci=np.quantile(rng.choice(v,(5000,len(v)),replace=True).mean(1),[.025,.975]);trim=(v.sum()-np.sort(v)[-2:].sum())/len(v)
 lines.append(f'- {name}, observed best offset {best.method}: mean {v.mean():.2f} bps/day; descriptive interval [{ci[0]:.2f}, {ci[1]:.2f}]; removing two best days leaves {trim:.2f} bps per original sampled day.')
lines+=['','## Broader discovery completed','', '187 non-EMA features, 8,269 replay configurations. Bar-based single-position leaders at +1 bp/side: up_down_return_ratio rule115 +193.98%, market_return rule78 +146.61%, positive_jump_fraction rule338 +133.52%. These are selected discovery returns, not quote-confirmed annual performance. Their best five trades account for roughly 42%,36%,36% of additive gross profit; positive months 10,10,9. Each trades roughly once per day with a 240-minute hold. All three included in this quote comparison.','', 'Artifacts: quote_expanded/design.json, manifest.parquet, replays.parquet, summary.parquet, daily.parquet, missing.json and raw quote windows. Reproduce with tools/intraday_quote_expanded.py and tools/intraday_quote_expanded_report.py.']
Path('docs/research/'+('V3_QUOTE_LEADERS_FULL_2026-09-28.md' if full else 'V3_QUOTE_EXPANDED_2026-09-28.md')).write_text('\n'.join(lines)+'\n')
print(s.sort_values('bps_per_sample_day',ascending=False).groupby('strategy',sort=False).head(1).to_string(index=False))
