import json,pandas as pd
from pathlib import Path
O=Path('D:/AlgoResearch/Quant-Pipeline-V3/runs/v3_comprehensive_20260923/research/intraday_strategy_20260928');D=O/'spread_both_legs';s=pd.read_parquet(D/'both_legs_summary.parquet');r=pd.read_parquet(D/'both_legs_replays.parquet');ps=pd.read_parquet(D/'paired_summary.parquet');pr=pd.read_parquet(D/'paired_execution.parquet');a=json.loads((O/'price_axes.json').read_text());out=[]
for name in sorted(s.strategy.unique()):
 paired='paired' in name;g=ps if paired else s[s.strategy==name];tr=pr if paired else r[r.strategy==name];best=g.sort_values('bps_attempt',ascending=False).iloc[0];market=g[(g.entry_method=='market')&(g.exit_method=='market')].iloc[0];x=tr[(tr.entry_method==best.entry_method)&(tr.exit_method==best.exit_method)].copy();x['month']=[str(a['days'][d])[:7] for d in x.day]
 out.append({'strategy':name,'attempts':int(best.attempts),'market_bps_attempt':market.bps_attempt,'entry_offset':best.entry_method,'exit_offset':best.exit_method,'best_bps_attempt':best.bps_attempt,'fills':int(best.matched_pairs if paired else best.entry_fills),'unmatched_unwinds':int(best.unmatched_unwinds) if paired else 0,'positive_sample_months':int((x.groupby('month').bps.sum()>0).sum()),'trim3_bps_attempt':x.bps.nsmallest(len(x)-3).sum()/len(x)})
f=pd.DataFrame(out);f.to_parquet(D/'decision_summary.parquet',index=False);print(f.to_string(index=False))
text='# Edge-spread and long-only research - 2026-09-28\n\nScreened all canonical r5 raw-return surfaces, excluding known misaligned EMA distance. Required at least 10,000 observations on each leg, long mean >=3 bp and short mean <=-3 bp. 631 pair/horizon combinations qualified. Ranked spread divided by sqrt(hold), tempered by smaller-leg frequency n/(n+10000). Selected 16 distinct pairs with a two-use feature cap. Separately selected eight high-margin long-only time subsets (>=5 bp, >=5,000 observations, >=10 pooled positive months). Correlated breakout/reclaim definitions are not independent confirmations.\n\nReplayed exact eligible signals with a one-minute entry delay and highest contemporaneous trailing dollar volume priority. Long-only: 1/5 positions. Matched spread: 1/5 pairs, simultaneous opposite cells of the same edge, same holding horizon, no shared active ticker. Paired capital is 50/50 long/short per pair, total gross notional 100%, not two full-equity legs. Dollar neutral is not necessarily beta neutral. Actual simultaneous availability reduces pooled frequency substantially. Positions exit before close, including early closes. Cost ladder -1,0,1,2,3,4,5 bp/side saved.\n\n## Quote samples\n\nFour seeded random opportunities per month per strategy. Paired samples select whole pairs. 64 entry/exit offset combinations, market plus -1 through5 bp. Unfilled entries cancel after60 seconds. If exactly one pair leg fills, that leg is unwound at the entry expiry quote; no invented matching fill and no free one-leg exposure. Both-filled pair returns average the two leg returns. Exit limits have a60-second market fallback, capped five minutes before close. Quote-price returns have no hypothetical cost/rebate overlay. Strict move-through remains a queue/size-unverified fill proxy. No sample annualization.\n\n| Strategy | Attempts | Market bps/attempt | Best entry/exit | Best bps/attempt | Filled trades/pairs | Unmatched unwinds | Positive sampled months | Excluding best3 |\n|---|---:|---:|---|---:|---:|---:|---:|---:|\n'
for z in f.itertuples():text+=f'| {z.strategy} | {z.attempts} | {z.market_bps_attempt:.3f} | {z.entry_offset}/{z.exit_offset} | {z.best_bps_attempt:.3f} | {z.fills} | {z.unmatched_unwinds} | {z.positive_sample_months}/12 | {z.trim3_bps_attempt:.3f} |\n'
text+='\nBest-grid values are selected discovery maxima. Capital conflicts from extended limit exits require full event replay before portfolio claims.\n\n## Bar diagnostics (not quote performance)\n\n'
b=pd.read_parquet(O/'spread_replay/results.parquet');rules=pd.read_parquet(O/'spread_replay/rules.parquet')
for ident,mode,slots in [(12,'long',1),(12,'paired',5),(19,'long',5)]:
 z=b[(b.mechanism_id==ident)&(b['mode']==mode)&(b.slots==slots)&(b.cost==1)].iloc[0];rule=rules[rules.mechanism_id==ident].iloc[0]
 text+=f'- {ident}/{mode}/{slots}: {rule.feature_a} x {rule.feature_b}; {rule.horizon}m hold. At1 bp/side: {z.return_pct:.2f}%, daily DD {z.daily_dd_pct:.2f}%, {z.trades_day:.2f} trades or pairs/day, {z.positive_months}/12 positive months.\n'
text+='\nArtifacts: '+str(O)+' under spread_replay, spread_quote_sample and spread_both_legs. Detailed rules, coverage, cost ladder, legs, paired execution and quote grids saved. May2026 onward untouched.\n'
Path('docs/research/V3_SPREAD_LONG_ONLY_2026-09-28.md').write_text(text,encoding='utf-8');p=Path('docs/research/RESEARCH_INDEX.md');t=p.read_text(encoding='utf-8');link='V3_SPREAD_LONG_ONLY_2026-09-28.md'
if link not in t:p.write_text(t+'\n## Edge spreads and long-only\n\n[Matched spread and high-margin long-only tests]('+link+'). Pair-aware unmatched-leg unwind included.\n',encoding='utf-8')
